service: moh-deh2-spot-hero

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

  stage: api
  region: us-west-2

  # you can define service wide environment variables here
  environment:
    ACCESS_TOKEN: ${env:AWS_ACCESS_KEY_ID }
    SECRET_KEY: ${env:AWS_SECRET_ACCESS_KEY}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  app:
    handler: bin/main
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
resources:
  Resources:
    VehicleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VehicleSpot
        AttributeDefinitions:
          - AttributeName: vehicle_id
            AttributeType: S
        KeySchema:
          - AttributeName: vehicle_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    ReservationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ReservationSpot
        AttributeDefinitions:
          - AttributeName: reservation_id
            AttributeType: S
        KeySchema:
          - AttributeName: reservation_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    FacilityTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FacilitySpot
        AttributeDefinitions:
          - AttributeName: facility_id
            AttributeType: S
          - AttributeName: latitude
            AttributeType: N
          - AttributeName: longitude
            AttributeType: N
        KeySchema:
          - AttributeName: facility_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: "Facility_index"
            KeySchema:
              - AttributeName: latitude
                KeyType: HASH
              - AttributeName: longitude
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5